# Generated by Django 5.2.14 on 2026-05-19 17:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorfield.fields.ColorField(default='#0066cc', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#ff9900', image_field=None, max_length=25, samples=None)),
                ('accent_color', colorfield.fields.ColorField(default='#00cc66', image_field=None, max_length=25, samples=None)),
                ('background_type', models.CharField(choices=[('color', 'Color'), ('gradient', 'Gradient'), ('image', 'Image')], default='color', max_length=10)),
                ('background_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('background_gradient', models.CharField(default='linear-gradient(135deg, #ffffff, #f5f5f5)', help_text='CSS gradient format, e.g., linear-gradient(135deg, #fff, #f5f5f5)', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('text_color', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None)),
                ('heading_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('button_color', colorfield.fields.ColorField(default='#0066cc', image_field=None, max_length=25, samples=None)),
                ('button_text_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('button_hover_color', colorfield.fields.ColorField(default='#0052a3', image_field=None, max_length=25, samples=None)),
                ('button_hover_text_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('link_color', colorfield.fields.ColorField(default='#0066cc', image_field=None, max_length=25, samples=None)),
                ('link_hover_color', colorfield.fields.ColorField(default='#0052a3', image_field=None, max_length=25, samples=None)),
                ('header_background', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('footer_background', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None)),
                ('footer_text_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name_plural': 'Website Customization',
            },
        ),
    ]
