# Generated by Django 5.2.14 on 2026-05-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_websitecustomization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitecustomization',
            name='background_image',
        ),
    ]
