# Generated by Django 5.2.14 on 2026-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_websitecustomization_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecustomization',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
